version: '3.1'
services:
  database:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: jonas
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: parquimetro
    container_name: parquimetrodb
    ports:
      - "5432:5432"
    volumes:
      - "$HOME/developer/postech/volumes/parquimetrodb:/var/lib/postgresql/data"
    networks:
      - parquimetro-networks

  parquimetro-app:
    build:
      dockerfile: ECS.dockerfile
      context: .
    image: jonasflorencio/parquimetro:3.0
    container_name: parquimetro-app
    volumes:
      - /home/developer/postech/parquimetro:/home/jonas/developer/postech/volumes/parquimetro
    ports:
      - "8080:8080"
    networks:
      - parquimetro-networks
    depends_on:
      - "database"
    links:
      - "database"

networks:
  parquimetro-networks:
    driver: bridge