app:
  date:
    format: yyyy-MM-dd
spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    username: jonas
    assword: abc1234
    url: "jdbc:h2:mem:techchallange?createDatabaseIfNotExist=true"
  web:
    locale: pt_BR